version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_hr
    environment:
      POSTGRES_DB: hr_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./employee_data.csv:/tmp/employee_data.csv:ro
    networks:
      - metabase_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    environment:
      JAVA_TIMEZONE: Asia/Jakarta
      MB_SITE_URL: http://localhost:3000
    networks:
      - metabase_net
    restart: unless-stopped

volumes:
  metabase-data:
  postgres_data:

networks:
  metabase_net:
    driver: bridge
